// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLG1gu57O6E2HpQ1A5sshswIddESD_GU',
    appId: '1:461629215116:web:fed288871825889145c6a9',
    messagingSenderId: '461629215116',
    projectId: 'chatapp1-741e5',
    authDomain: 'chatapp1-741e5.firebaseapp.com',
    storageBucket: 'chatapp1-741e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkBCQbKqSLlRwVrzAHR3tab3msYN3B9w',
    appId: '1:461629215116:android:d23c0b06f695005345c6a9',
    messagingSenderId: '461629215116',
    projectId: 'chatapp1-741e5',
    storageBucket: 'chatapp1-741e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_cqLgxpPFRHVhxJ5s3iSiZOms8OI2o4',
    appId: '1:461629215116:ios:bccdb400fb019cb445c6a9',
    messagingSenderId: '461629215116',
    projectId: 'chatapp1-741e5',
    storageBucket: 'chatapp1-741e5.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_cqLgxpPFRHVhxJ5s3iSiZOms8OI2o4',
    appId: '1:461629215116:ios:bccdb400fb019cb445c6a9',
    messagingSenderId: '461629215116',
    projectId: 'chatapp1-741e5',
    storageBucket: 'chatapp1-741e5.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLG1gu57O6E2HpQ1A5sshswIddESD_GU',
    appId: '1:461629215116:web:6820c22a584cdb3645c6a9',
    messagingSenderId: '461629215116',
    projectId: 'chatapp1-741e5',
    authDomain: 'chatapp1-741e5.firebaseapp.com',
    storageBucket: 'chatapp1-741e5.appspot.com',
  );
}
